services:
  - type: web
    name: medical-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
    plan: free
    healthCheckPath: /
    autoDeploy: true
    
